import { useEffect,useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Sparkles,Target,Brain,TrendingUp,ArrowRight,RefreshCw,CheckCircle2,LockKeyhole,Compass,Radar,Zap } from 'lucide-react'
import { apiFetch } from '../../lib/api'
import { Page,Container,Card,Eyebrow,Button,Badge,ScoreRing,ProgressBar,SectionHeading,Skeleton } from '../../components/common/UI'
const fallbackStages=['Profile','Career Assessment','Career Twin','Career Path','Skill Gap','Learning Roadmap','Job Match','Application','Interview','Career Ready']
export default function CareerJourney(){const nav=useNavigate();const [d,setD]=useState({});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [scenario,setScenario]=useState('');
 const load=async()=>{setLoading(true);const [j,t,r,radar]=await Promise.all([apiFetch('/ai-career/journey').catch(()=>null),apiFetch('/ai-career/twin').catch(()=>null),apiFetch('/ai-career/readiness').catch(()=>null),apiFetch('/ai-career/radar').catch(()=>null)]);setD({journey:j?.journey,twin:t?.twin,readiness:r?.readiness||r,radar:radar?.radar});setLoading(false)};useEffect(()=>{load()},[])
 const run=async(type,path,body={})=>{setBusy(type);const r=await apiFetch(path,{method:'POST',body:JSON.stringify(body)}).catch(()=>null);setD(x=>({...x,[type]:r?.simulation||r?.radar||r?.twin||r?.readiness||r?.match||r?.gap}));setBusy('')}
 if(loading)return <Page><Container><Skeleton className="h-64"/><div className="mt-5 grid md:grid-cols-2 gap-4"><Skeleton className="h-60"/><Skeleton className="h-60"/></div></Container></Page>
 const journey=d.journey||{};const stages=journey.stages?.length?journey.stages:fallbackStages.map((name,i)=>({name,status:i===0?'current':'locked',headline:'Complete the previous step to unlock this stage.'}));const r=d.readiness||{};const twin=d.twin||{}
 return <Page><Container className="space-y-5"><section className="ui-card ui-card-glow hero-command"><div><Eyebrow icon={RouteIcon}>Personalized Career Journey</Eyebrow><h1>One path. No career guesswork.</h1><p>Every insight leads to a concrete next step — from profile signal to interview confidence and career readiness.</p><div className="hero-actions"><Button className="bg-white !text-gray-900" onClick={load}><RefreshCw size={15}/>Refresh journey</Button><Button variant="secondary" className="!bg-white/10 !text-white !border-white/20" onClick={()=>nav('/jobs')}>Explore opportunities <ArrowRight size={15}/></Button></div></div><div className="next-action"><div className="label">Current stage</div><h3>{journey.current_stage||stages.find(s=>s.status==='current')?.name||'Profile'}</h3><p>{journey.north_star||'Build evidence that compounds.'}</p><ProgressBar value={journey.progress_percent||0} label="Journey progress"/></div></section>
 <Card><SectionHeading eyebrow="The operating system" title="Your 10-step career path" description="Completed stages build evidence. The current stage is where your next best action lives."/><div className="timeline">{stages.map((s,i)=>{const status=s.status||'locked';return <button key={s.name} onClick={()=>{if(s.name.includes('Assessment'))nav('/career/assessment');else if(s.name.includes('Roadmap'))nav('/career/roadmap');else if(s.name.includes('Skill'))nav('/career/skills');else if(s.name.includes('Application'))nav('/jobs');else if(s.name.includes('Interview'))nav('/career/interview')}} className={`timeline-node text-left ${status==='done'?'done':''} ${status==='current'?'current':''}`}><div className="timeline-dot">{status==='done'?<CheckCircle2 size={18}/>:status==='current'?<Zap size={18}/>:<LockKeyhole size={17}/>}</div><div><strong>{s.name}</strong><span>{status==='current'?'Current focus':status==='done'?'Completed':'Unlock after previous step'}</span></div></button>})}</div></Card>
 <div className="dashboard-grid"><Card><SectionHeading eyebrow="Career Twin" title={twin.headline||'Your professional identity'} description={twin.identity_statement||'Your AI twin summarizes how your strengths and preferences translate into career direction.'}/><div className="flex flex-wrap gap-2">{(twin.strengths||[]).slice(0,7).map(x=><Badge tone="primary" key={x}>{x}</Badge>)}</div><div className="grid md:grid-cols-2 gap-4 mt-5"><div className="ai-strip"><strong>Best fit</strong><p className="text-sm text-gray-600">{twin.best_fit_environments?.[0]||'Collaborative, growth-oriented teams'}</p></div><div className="ai-strip"><strong>90-day move</strong><p className="text-sm text-gray-600">{twin.next_90_days?.[0]||'Build one portfolio proof point'}</p></div></div></Card><Card><div className="flex items-center gap-5"><ScoreRing value={r.overall_score||0}/><div><Eyebrow icon={Target}>Career readiness</Eyebrow><h3 className="text-xl font-black mt-2">{r.verdict||'Build your baseline'}</h3><p className="text-sm text-gray-500 mt-1">Your score changes as you build skills and evidence.</p></div></div><div className="space-y-3 mt-6">{(r.dimensions||[]).slice(0,4).map(x=><ProgressBar key={x.name} value={x.score} label={x.name}/>)}</div></Card></div>
 <Card><SectionHeading eyebrow="Opportunity Radar" title="Move from insight to market" description="The radar connects your current signal to live opportunities." action={<Button variant="secondary" onClick={()=>run('radar','/ai-career/radar')} disabled={busy==='radar'}><Radar size={15}/>{busy==='radar'?'Scanning...':'Scan now'}</Button>}/>{d.radar?.opportunities?.length?<div className="grid md:grid-cols-3 gap-4">{d.radar.opportunities.slice(0,3).map(o=><div className="job-card" key={o.title}><Badge tone="success">{Math.round(o.fit_score)}% fit</Badge><h3>{o.title}</h3><p className="text-sm text-gray-500">{o.reason}</p><p className="text-sm font-bold text-primary mt-3">{o.action}</p></div>)}</div>:<div className="ai-strip"><strong>Your radar is ready.</strong><p className="text-sm text-gray-600">Scan when you want to prioritize your next applications.</p></div>}</Card>
 <Card><SectionHeading eyebrow="Decision lab" title="What happens if you change direction?" description="Test a learning or career choice without leaving your journey."/><div className="flex flex-col sm:flex-row gap-3"><input aria-label="Career scenario" value={scenario} onChange={e=>setScenario(e.target.value)} placeholder="e.g. Spend 6 weeks on SQL + analytics projects" className="flex-1 px-4 py-3 rounded-xl border border-gray-200 bg-gray-50 outline-none focus:bg-white"/><Button disabled={busy==='simulation'||!scenario.trim()} onClick={()=>run('simulation','/ai-career/what-if',{scenario,baseReadiness:r})}>{busy==='simulation'?'Simulating...':'Run what-if'} <ArrowRight size={15}/></Button></div>{d.simulation&&<div className="ai-strip mt-4"><strong>Projected readiness: {Math.round(d.simulation.projected_score)}%</strong><p className="text-sm text-gray-600 mt-1">{d.simulation.benefits?.[0]||'Review the assumptions before committing.'}</p></div>}</Card>
 </Container></Page>}
const RouteIcon=Compass
