import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Briefcase, FileText, Bookmark, Sparkles, ArrowRight, Target, Route, Radar, CheckCircle2, Clock3 } from 'lucide-react'
import { supabase } from '../../config/supabase'
import { apiFetch } from '../../lib/api'
import { useAuth } from '../../context/AuthContext'
import { Page, Container, Card, Eyebrow, Button, Badge, ScoreRing, ProgressBar, SectionHeading, Skeleton } from '../../components/common/UI'

export default function StudentDashboard(){
 const {user,profile}=useAuth(); const [stats,setStats]=useState({totalApplications:0,pendingApplications:0,savedJobs:0,recentApplications:[]}); const [ai,setAi]=useState({}); const [loading,setLoading]=useState(true)
 useEffect(()=>{if(user) load()},[user])
 const load=async()=>{setLoading(true);try{const [apps,saved,twin,readiness,journey,jobs]=await Promise.all([supabase.from('applications').select('*,jobs(*)').eq('user_id',user.id).order('applied_at',{ascending:false}),supabase.from('saved_jobs').select('id').eq('user_id',user.id),apiFetch('/ai-career/twin').catch(()=>null),apiFetch('/ai-career/readiness').catch(()=>null),apiFetch('/ai-career/journey').catch(()=>null),apiFetch('/jobs').catch(()=>null)]);const applications=apps.data||[];setStats({totalApplications:applications.length,pendingApplications:applications.filter(a=>a.status==='pending').length,savedJobs:(saved.data||[]).length,recentApplications:applications.slice(0,4)});setAi({twin:twin?.twin,readiness:readiness?.readiness||readiness,journey:journey?.journey,jobs:jobs?.jobs||[]})}finally{setLoading(false)}}
 if(loading)return <Page><Container><div className="space-y-4"><Skeleton className="h-64"/><div className="metric-grid">{[1,2,3,4].map(i=><Skeleton key={i} className="h-28"/>)}</div></div></Container></Page>
 const readiness=ai.readiness; const journey=ai.journey; const next=journey?.stages?.find(s=>s.status==='current')||journey?.stages?.find(s=>s.status!=='done'); const jobs=ai.jobs.slice(0,3)
 return <Page><Container className="space-y-5">
  <section className="ui-card ui-card-glow hero-command"><div><Eyebrow icon={Sparkles}>Career Command Center</Eyebrow><h1>Turn uncertainty into your next move.</h1><p>Welcome back, {profile?.full_name?.split(' ')[0]||'there'}. Your profile, AI insights and live opportunities are connected in one career operating system.</p><div className="hero-actions"><Link to="/career" className="ui-btn ui-btn-primary bg-white !text-gray-900"><Sparkles size={16}/>Open Career Intelligence</Link><Link to="/jobs" className="ui-btn ui-btn-secondary !bg-white/10 !text-white !border-white/20">Explore jobs <ArrowRight size={16}/></Link></div></div><div className="next-action"><div className="label">Recommended next action</div><h3>{next?.name||'Build your career profile'}</h3><p>{next?.headline||'Complete your profile so StudentHub can make stronger career recommendations.'}</p><Link to={next?.name?.includes('Assessment')?'/career/assessment':'/career'} className="ui-btn ui-btn-primary w-full">Take the next step <ArrowRight size={15}/></Link></div></section>
  <div className="metric-grid"><div className="metric-card"><div className="metric-icon"><FileText size={18}/></div><div className="metric-value">{stats.totalApplications}</div><div className="metric-label">Applications</div></div><div className="metric-card"><div className="metric-icon"><Clock3 size={18}/></div><div className="metric-value">{stats.pendingApplications}</div><div className="metric-label">Awaiting review</div></div><div className="metric-card"><div className="metric-icon"><Bookmark size={18}/></div><div className="metric-value">{stats.savedJobs}</div><div className="metric-label">Saved opportunities</div></div><div className="metric-card"><div className="metric-icon"><Target size={18}/></div><div className="metric-value">{readiness?`${Math.round(readiness.overall_score)}%`:'—'}</div><div className="metric-label">Career readiness</div></div></div>
  <div className="dashboard-grid"><Card><SectionHeading eyebrow="AI Career Twin" title="Your professional signal" description={ai.twin?.identity_statement||'Your Career Twin becomes more useful as your profile and assessment become richer.'} action={<Link className="arrow-link" to="/career">Open twin <ArrowRight size={15}/></Link>}/><div className="three-grid">{(ai.twin?.strengths||['Curiosity','Problem solving','Growth mindset']).slice(0,3).map(s=><div className="ai-strip" key={s}><span className="ui-badge ui-badge-primary">Strength</span><strong className="mt-2">{s}</strong><span className="text-xs text-gray-500">Signals from your career profile</span></div>)}</div></Card><Card><div className="flex items-center gap-5"><ScoreRing value={readiness?.overall_score||0}/><div><Eyebrow icon={Target}>Readiness</Eyebrow><h3 className="text-xl font-extrabold mt-2">{readiness?.verdict||'Build your baseline'}</h3><p className="text-sm text-gray-500 mt-1">{readiness?.dimensions?.length||0} dimensions tracked</p></div></div><div className="mt-6 space-y-3">{(readiness?.dimensions||[]).slice(0,3).map(d=><ProgressBar key={d.name} value={d.score} label={d.name}/>)}</div><Link to="/career" className="ui-btn ui-btn-secondary mt-5 w-full">Improve my readiness</Link></Card></div>
  <Card><SectionHeading eyebrow="Opportunity Radar" title="Roles worth your attention" description="Start with opportunities that align with your current signal and next skill moves." action={<Link className="arrow-link" to="/jobs">View all <ArrowRight size={15}/></Link>}/><div className="grid md:grid-cols-3 gap-4">{jobs.map(job=><Link className="job-card" to={`/jobs/${job.id}`} key={job.id}><Badge tone="primary">{job.job_type?.replace('-',' ')||'role'}</Badge><h3>{job.title}</h3><p className="text-sm text-gray-500">{job.company_name}</p><div className="job-meta mt-3"><span><Briefcase size={13}/>{job.work_mode||'Flexible'}</span><span>{job.location||'Location flexible'}</span></div><div className="job-footer"><span className="match-score">AI match ready</span><ArrowRight size={16} className="text-gray-400"/></div></Link>)}{!jobs.length&&<div className="col-span-full text-sm text-gray-500">No live opportunities yet. <Link className="text-primary font-bold" to="/jobs">Browse the marketplace.</Link></div>}</div></Card>
  <div className="dashboard-grid"><Card><SectionHeading eyebrow="Career Journey" title={journey?.current_stage||'Start your journey'} description={journey?.north_star||'Your career plan links every action into one path.'} action={<Link className="arrow-link" to="/career/journey">Open journey <ArrowRight size={15}/></Link>}/><ProgressBar value={journey?.progress_percent||0} label="Journey progress"/><div className="mt-5 flex items-center gap-3 text-sm"><CheckCircle2 className="text-green-600" size={17}/><span>One connected path from profile to career ready.</span></div></Card><Card><SectionHeading eyebrow="Applications" title="Latest activity" action={<Link className="arrow-link" to="/dashboard/applications">Track all <ArrowRight size={15}/></Link>}/>{stats.recentApplications.length?<ul className="list-clean">{stats.recentApplications.map(a=><li key={a.id}><span className="dot"/><div><strong>{a.jobs?.title||'Application'}</strong><div className="text-xs text-gray-500">{a.jobs?.company_name||'Company'} · <span className="capitalize">{a.status}</span></div></div></li>)}</ul>:<div className="text-sm text-gray-500">Your next application can become your first data point. <Link className="text-primary font-bold" to="/jobs">Find a role.</Link></div>}</Card></div>
 </Container></Page>
}
