import express from 'express'
import { supabase, isSupabaseConfigured } from '../config/supabase.js'
import { demoCareers, demoJobs, demoStore } from '../config/demoData.js'
import { authenticate } from '../middleware/auth.js'
import { aiRateLimit } from '../middleware/aiRateLimit.js'
import { generateCareerTwin, generateCareerReadiness, generateExplainableJobMatch, generateJobSkillGap, generateApplicationCopilot, generateInterviewTurn, generateCareerWhatIf, generateOpportunityRadar, generateCareerJourney } from '../services/geminiService.js'

const router = express.Router()
const own = (data, userId) => data?.user_id === userId
const fallbackTwin = (a) => ({headline:'A practical, growth-oriented career profile',strengths:['Curiosity','Learning through practice'],motivators:['Visible progress','Meaningful work'],work_style:'A balanced mix of independent focus and collaboration.',best_fit_environments:['Teams with mentorship','Project-based environments'],emerging_skills:['Communication','Portfolio building'],risks:['Scattered learning without a clear target'],next_90_days:['Choose one target career','Close the top skill gap','Build one portfolio proof'],identity_statement:'A learner turning interests into job-ready evidence.'})
const fallbackReadiness = (a, career) => { const skills=(a?.current_skills||[]).map(s=>String(s?.skill||s).toLowerCase()); const targets=career?.required_skills||[]; const hit=targets.filter(s=>skills.includes(String(s).toLowerCase())).length; const score=targets.length?Math.round(hit/targets.length*100):50; return {overall_score:score,dimensions:[{name:'Target skills',score,evidence:[`${hit} of ${targets.length} core skills found in the assessment`],next_step:'Close the highest-priority skill gap.'},{name:'Career direction',score:a?.career_goal?75:45,evidence:[a?.career_goal?'A career goal is recorded.':'No clear career goal recorded.'],next_step:'Keep one target role in focus.'},{name:'Evidence',score:45,evidence:['Portfolio evidence was not evaluated by the rule-based fallback.'],next_step:'Add projects and measurable proof.'}],top_gaps:targets.filter(s=>!skills.includes(String(s).toLowerCase())).slice(0,5),fastest_wins:['Finish one practical project','Update your resume','Practice one interview'],verdict:'Use this as a baseline while AI is unavailable.'} }
const fallbackMatch = (profile,job) => { const text=JSON.stringify(profile||{}).toLowerCase(); const words=[job?.title,job?.description,job?.category].filter(Boolean).join(' ').toLowerCase(); const overlap=(job?.required_skills||[]).filter(s=>text.includes(String(s).toLowerCase())).length; const score=Math.min(95,Math.max(35,55+overlap*10)); return {overall_score:score,verdict:score>=75?'Strong fit':'Promising fit with skill gaps',factors:[{name:'Skills',score,weight:45,evidence:`${overlap} relevant required skills were found.`,improvement:'Build proof for missing skills.'},{name:'Role alignment',score:words.includes(String(profile?.career_goal||'').toLowerCase())?85:60,weight:30,evidence:'Compared with the stated target and job description.',improvement:'Keep the application focused on this role.'},{name:'Evidence',score:45,weight:25,evidence:'Fallback cannot fully evaluate portfolio quality.',improvement:'Add project outcomes and measurable evidence.'}],strengths:['Relevant interests or skills detected'],gaps:(job?.required_skills||[]).slice(0,4),actions:['Review the skill gaps','Tailor your resume','Practice interview questions']} }
const fallbackGap = (profile,job) => { const skills=(profile?.current_skills||[]).map(s=>String(s?.skill||s).toLowerCase()); const gaps=(job?.required_skills||[]).filter(s=>!skills.includes(String(s).toLowerCase())); return {readiness_percent:Math.max(20,100-Math.min(80,gaps.length*12)),matches:(job?.required_skills||[]).filter(s=>skills.includes(String(s).toLowerCase())),gaps:gaps.slice(0,10).map((skill,i)=>({skill,priority:i<3?'high':'medium',current_level:'unknown',target_level:'working',why_it_matters:`${skill} is listed as important for this role.`,proof_to_build:`Build a small project that demonstrates ${skill}.`})),action_plan:['Start with the highest-priority gap','Build evidence through a project','Recheck the match after progress']} }
const fallbackCopilot=(profile,job)=>({fit_summary:'A truthful application should connect your existing evidence to the role requirements.',tailored_resume_bullets:['Highlight the strongest relevant project or course.','Place the most relevant skills near the top.','Add measurable outcomes only when you can verify them.'],cover_letter:`I am interested in the ${job?.title||'role'} because it aligns with my current skills and career direction. I would welcome the opportunity to contribute, learn quickly, and grow through practical work.`,evidence_to_highlight:['Relevant skills','Projects','Coursework or experience directly related to the role'],missing_evidence:['Role-specific measurable outcomes'],application_checklist:['Review the job requirements','Tailor your resume truthfully','Proofread before submitting']})

async function context(req, careerId) {
  if (!isSupabaseConfigured) {
    const assessment=demoStore.assessments.get(req.user.id)||null
    const profile=demoStore.profiles.get(req.user.id)||null
    const career=demoCareers.find(c=>c.id===careerId)||demoCareers[0]
    return {assessment,profile,career}
  }
  const [{data:assessment},{data:profile},{data:career}] = await Promise.all([
    supabase.from('career_assessments').select('*').eq('user_id',req.user.id).maybeSingle(),
    supabase.from('profiles').select('*').eq('id',req.user.id).maybeSingle(),
    careerId ? supabase.from('careers').select('*').eq('id',careerId).maybeSingle() : Promise.resolve({data:null})
  ])
  return {assessment,profile,career}
}
async function jobFor(req, id){
  if(!isSupabaseConfigured) return demoJobs.find(j=>j.id===id)||null
  const {data,error}=await supabase.from('jobs').select('*').eq('id',id).single(); if(error) return null; return data
}
async function save(table, payload, conflict){ if(!isSupabaseConfigured)return null; let q=supabase.from(table).upsert(payload, conflict?{onConflict:conflict}:undefined); const {data,error}=await q.select().single(); if(error) throw error; return data }
function aiError(res,e){ const status=e?.status||503; if(String(e?.code||'').startsWith('AI_')) return res.status(status).json({error:e.message,code:e.code,aiUnavailable:['AI_NOT_CONFIGURED','AI_UNAVAILABLE','AI_TIMEOUT','AI_RATE_LIMITED','AI_AUTH_ERROR'].includes(e.code)}); return res.status(503).json({error:'AI service is temporarily unavailable',code:'AI_UNAVAILABLE',aiUnavailable:true}) }

router.get('/journey',authenticate,async(req,res)=>{try{const {assessment}=await context(req);const matches=isSupabaseConfigured?(await supabase.from('career_matches').select('*,careers(*)').eq('user_id',req.user.id).order('match_score',{ascending:false})).data:(demoStore.matches.get(req.user.id)||[]);const twin=isSupabaseConfigured?(await supabase.from('career_twins').select('*').eq('user_id',req.user.id).maybeSingle()).data:null;const input={assessment,matches:matches?.slice(0,3),twin:twin?.data||null};let journey;try{journey=await generateCareerJourney(input)}catch{journey={north_star:'Turn your strongest interests into job-ready evidence.',current_stage:assessment?.status==='completed'?'Career Assessment':'Profile',progress_percent:assessment?.status==='completed'?25:10,stages:[{name:'Profile',status:'done',headline:'Know your starting point.',actions:['Keep your profile current']},{name:'Career Assessment',status:assessment?.status==='completed'?'done':'current',headline:'Discover your best-fit directions.',actions:['Complete the assessment']},{name:'Career Twin',status:'next',headline:'Understand how you work best.',actions:['Generate your twin']},{name:'Skill Gap',status:'next',headline:'Know what to learn next.',actions:['Analyze your top career']},{name:'Roadmap',status:'next',headline:'Turn gaps into weekly progress.',actions:['Generate your roadmap']},{name:'Job Match',status:'next',headline:'Find roles worth pursuing.',actions:['Explore matching jobs']},{name:'Application',status:'next',headline:'Apply with evidence, not guesses.',actions:['Tailor an application']},{name:'Interview',status:'next',headline:'Practice under pressure.',actions:['Run a mock interview']},{name:'Readiness',status:'next',headline:'Measure your job readiness.',actions:['Check readiness']}],weekly_focus:['Complete the next unfinished stage','Build one proof item','Review one real job'],celebration:'Every completed step becomes evidence you can show an employer.'}} if(isSupabaseConfigured) await save('career_journeys',{user_id:req.user.id,data:journey,updated_at:new Date().toISOString()},'user_id'); res.json({journey})}catch(e){console.error(e);res.status(500).json({error:'Failed to load career journey'})}})

router.post('/twin',authenticate,aiRateLimit,async(req,res)=>{try{const {assessment,profile}=await context(req);let data;try{data=await generateCareerTwin({assessment,profile})}catch(e){data=fallbackTwin(assessment)};const saved=await save('career_twins',{user_id:req.user.id,data,updated_at:new Date().toISOString()},'user_id');if(!isSupabaseConfigured)demoStore.careerTwins?.set?.(req.user.id,data);res.json({twin:saved?.data||data,usedFallback:!process.env.GEMINI_API_KEY})}catch(e){aiError(res,e)}})
router.get('/twin',authenticate,async(req,res)=>{try{if(!isSupabaseConfigured)return res.json({twin:demoStore.careerTwins?.get?.(req.user.id)||null});const {data,error}=await supabase.from('career_twins').select('*').eq('user_id',req.user.id).maybeSingle();if(error)throw error;res.json({twin:data?.data||null})}catch(e){res.status(500).json({error:'Failed to fetch career twin'})}})

router.post('/readiness',authenticate,aiRateLimit,async(req,res)=>{try{let {career_id}=req.body||{}; const base=await context(req,career_id); if(!career_id && isSupabaseConfigured){const r=await supabase.from('career_matches').select('career_id,careers(*)').eq('user_id',req.user.id).order('match_score',{ascending:false}).limit(1).maybeSingle(); career_id=r.data?.career_id||null; base.career=r.data?.careers||base.career} const {assessment,profile,career}=base; if(!career)return res.status(404).json({error:'Career not found'});let data;try{data=await generateCareerReadiness({assessment,profile,career})}catch(e){data=fallbackReadiness(assessment,career)};const saved=await save('career_readiness_scores',{user_id:req.user.id,career_id,overall_score:data.overall_score,data,updated_at:new Date().toISOString()});res.json({readiness:saved?.data||data,score:data.overall_score,usedFallback:!process.env.GEMINI_API_KEY})}catch(e){aiError(res,e)}})
router.get('/readiness',authenticate,async(req,res)=>{try{if(!isSupabaseConfigured)return res.json({readiness:null});const {data,error}=await supabase.from('career_readiness_scores').select('*').eq('user_id',req.user.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;res.json({readiness:data?.data||null,score:data?.overall_score||0})}catch(e){res.status(500).json({error:'Failed to fetch readiness'})}})

router.post('/jobs/:jobId/match',authenticate,aiRateLimit,async(req,res)=>{try{const job=await jobFor(req,req.params.jobId);if(!job)return res.status(404).json({error:'Job not found'});const {assessment,profile,career}=await context(req);let data;try{data=await generateExplainableJobMatch({assessment,profile,career,job})}catch(e){data=fallbackMatch(profile||assessment,job)}const saved=await save('job_match_explanations',{user_id:req.user.id,job_id:req.params.jobId,score:data.overall_score,data,updated_at:new Date().toISOString()},'user_id,job_id');res.json({match:saved?.data||data,score:data.overall_score,usedFallback:!process.env.GEMINI_API_KEY})}catch(e){aiError(res,e)}})
router.get('/jobs/:jobId/match',authenticate,async(req,res)=>{try{if(!isSupabaseConfigured)return res.json({match:null});const {data,error}=await supabase.from('job_match_explanations').select('*').eq('user_id',req.user.id).eq('job_id',req.params.jobId).maybeSingle();if(error)throw error;res.json({match:data?.data||null,score:data?.score||0})}catch(e){res.status(500).json({error:'Failed to fetch job match'})}})

router.post('/jobs/:jobId/gap',authenticate,aiRateLimit,async(req,res)=>{try{const job=await jobFor(req,req.params.jobId);if(!job)return res.status(404).json({error:'Job not found'});const {assessment,profile}=await context(req);let data;try{data=await generateJobSkillGap({assessment,profile,job})}catch(e){data=fallbackGap(profile||assessment,job)}const saved=await save('job_skill_gaps',{user_id:req.user.id,job_id:req.params.jobId,data,updated_at:new Date().toISOString()},'user_id,job_id');res.json({gap:saved?.data||data,usedFallback:!process.env.GEMINI_API_KEY})}catch(e){aiError(res,e)}})
router.get('/jobs/:jobId/gap',authenticate,async(req,res)=>{try{if(!isSupabaseConfigured)return res.json({gap:null});const {data,error}=await supabase.from('job_skill_gaps').select('*').eq('user_id',req.user.id).eq('job_id',req.params.jobId).maybeSingle();if(error)throw error;res.json({gap:data?.data||null})}catch(e){res.status(500).json({error:'Failed to fetch job skill gap'})}})

router.post('/jobs/:jobId/copilot',authenticate,aiRateLimit,async(req,res)=>{try{const job=await jobFor(req,req.params.jobId);if(!job)return res.status(404).json({error:'Job not found'});const {assessment,profile}=await context(req);let data;try{data=await generateApplicationCopilot({assessment,profile,job,application:req.body?.application||null})}catch(e){data=fallbackCopilot(profile||assessment,job)}const saved=await save('application_copilot_drafts',{user_id:req.user.id,job_id:req.params.jobId,data,updated_at:new Date().toISOString()});res.json({copilot:saved?.data||data,usedFallback:!process.env.GEMINI_API_KEY})}catch(e){aiError(res,e)}})

router.post('/interviews',authenticate,aiRateLimit,async(req,res)=>{try{const {jobId,roleTitle}=req.body||{};const job=jobId?await jobFor(req,jobId):null;const {assessment,profile}=await context(req);let turn;try{turn=await generateInterviewTurn({assessment,profile,job,roleTitle,answer:null})}catch(e){turn={question:`Tell me about a project that shows you can succeed as a ${roleTitle||job?.title||'candidate'}.`,category:'Behavioral',difficulty:'medium',what_good_answers_show:['Clear ownership','Specific actions','Results and learning'],evaluation:{score:0,strengths:[],improvements:[],better_answer:''},next_question:'What was the hardest part of that project?'}};if(!isSupabaseConfigured){const id=`demo-interview-${Date.now()}`;demoStore.interviews?.set?.(id,{id,user_id:req.user.id,job_id:jobId,role_title:roleTitle||job?.title,turns:[turn],status:'active'});return res.json({session:{id,turns:[turn],role_title:roleTitle||job?.title}})}const {data,error}=await supabase.from('interview_sessions').insert({user_id:req.user.id,job_id:jobId||null,role_title:roleTitle||job?.title||'Target role',turns:[turn]}).select().single();if(error)throw error;res.json({session:{...data,turns:data.turns}})}catch(e){aiError(res,e)}})
router.post('/interviews/:id/answer',authenticate,aiRateLimit,async(req,res)=>{try{let session;if(!isSupabaseConfigured)session=demoStore.interviews?.get?.(req.params.id);else {const r=await supabase.from('interview_sessions').select('*').eq('id',req.params.id).eq('user_id',req.user.id).single();session=r.data}if(!session)return res.status(404).json({error:'Interview session not found'});const {assessment,profile}=await context(req);const last=session.turns?.[session.turns.length-1];let turn;try{turn=await generateInterviewTurn({assessment,profile,job:await jobFor(req,session.job_id),roleTitle:session.role_title,previousQuestion:last?.question,answer:String(req.body?.answer||'').slice(0,6000)})}catch(e){turn={question:'What would you improve if you repeated that experience?',category:'Reflection',difficulty:'medium',what_good_answers_show:['Self-awareness','Specific learning'],evaluation:{score:60,strengths:['You gave an answer'],improvements:['Add specific evidence and outcomes'],better_answer:'Use a concise situation, action, result, and learning structure.'},next_question:'Tell me about a time you solved a difficult problem.'}}session.turns=[...(session.turns||[]),{answer:String(req.body?.answer||'').slice(0,6000)},turn];if(!isSupabaseConfigured){demoStore.interviews.set(session.id,session);return res.json({session})}const {data,error}=await supabase.from('interview_sessions').update({turns:session.turns,updated_at:new Date().toISOString()}).eq('id',session.id).eq('user_id',req.user.id).select().single();if(error)throw error;res.json({session:data})}catch(e){aiError(res,e)}})

router.post('/what-if',authenticate,aiRateLimit,async(req,res)=>{try{const {assessment,profile}=await context(req);const scenario=String(req.body?.scenario||'').slice(0,1200);if(!scenario)return res.status(400).json({error:'scenario is required'});let data;try{data=await generateCareerWhatIf({assessment,profile,scenario,baseReadiness:req.body?.baseReadiness||null})}catch(e){data={scenario_title:scenario,projected_score:60,score_change:10,assumptions:['The scenario is completed consistently.'],benefits:['Stronger evidence and confidence'],tradeoffs:['Time must be allocated to this goal'],next_actions:['Turn the scenario into a weekly plan'],recommendation:'This could be a useful experiment if it supports your target role.'}}if(isSupabaseConfigured)await supabase.from('career_what_if_runs').insert({user_id:req.user.id,scenario,data});res.json({simulation:data,usedFallback:!process.env.GEMINI_API_KEY})}catch(e){aiError(res,e)}})

router.post('/radar',authenticate,aiRateLimit,async(req,res)=>{try{const {assessment,profile,career}=await context(req);let jobs;if(!isSupabaseConfigured)jobs=demoJobs;else {const r=await supabase.from('jobs').select('*').eq('is_active',true).eq('status','active').limit(30);jobs=r.data||[]}let data;try{data=await generateOpportunityRadar({assessment,profile,career,jobs})}catch(e){data={summary:'Your radar is using a lightweight local ranking because AI is unavailable.',opportunities:jobs.slice(0,6).map((j,i)=>({title:j.title,type:'Job',reason:`Matches the ${j.category||'career'} area you are exploring.`,fit_score:Math.max(45,80-i*5),action:'Review the role and compare its skills with your profile.'})),watch_next:['New roles in your target category','Internships and entry-level roles','Opportunities matching your strongest skills']}}if(isSupabaseConfigured)await supabase.from('opportunity_radar_snapshots').insert({user_id:req.user.id,data});res.json({radar:data,usedFallback:!process.env.GEMINI_API_KEY})}catch(e){aiError(res,e)}})

export default router
