import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { Sparkles, Brain, Target, Route, Radar, Zap, ArrowRight, RefreshCw, ShieldCheck, AlertTriangle } from 'lucide-react'
import { apiFetch } from '../lib/api'
import { Page,Container,Card,Eyebrow,Button,Badge,ScoreRing,ProgressBar,SectionHeading,Skeleton } from '../components/common/UI'

export default function Career(){
 const [data,setData]=useState({});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [scenario,setScenario]=useState('')
 const load=async()=>{setLoading(true);const [t,r,j,radar]=await Promise.all([apiFetch('/ai-career/twin').catch(()=>null),apiFetch('/ai-career/readiness').catch(()=>null),apiFetch('/ai-career/journey').catch(()=>null),apiFetch('/ai-career/radar').catch(()=>null)]);setData({twin:t?.twin,readiness:r?.readiness||r,journey:j?.journey,radar:radar?.radar});setLoading(false)}
 useEffect(()=>{load()},[])
 const simulate=async()=>{if(!scenario.trim())return;setBusy('whatif');const r=await apiFetch('/ai-career/what-if',{method:'POST',body:JSON.stringify({scenario,baseReadiness:data.readiness})}).catch(()=>null);setData(d=>({...d,simulation:r?.simulation}));setBusy('')}
 if(loading)return <Page><Container><div className="space-y-4"><Skeleton className="h-56"/><div className="grid md:grid-cols-3 gap-4"><Skeleton className="h-44"/><Skeleton className="h-44"/><Skeleton className="h-44"/></div></div></Container></Page>
 const twin=data.twin||{};const readiness=data.readiness||{};const journey=data.journey||{};const dimensions=readiness.dimensions||[]
 return <Page><Container className="space-y-5">
  <section className="ui-card ui-card-glow hero-command"><div><Eyebrow icon={Brain}>AI Career Intelligence</Eyebrow><h1>Your career, modeled as a system.</h1><p>StudentHub turns scattered profile signals into a clear direction, measurable readiness and the next action worth taking.</p><div className="hero-actions"><Link className="ui-btn ui-btn-primary bg-white !text-gray-900" to="/career/journey">Open Career Journey <ArrowRight size={16}/></Link><button className="ui-btn ui-btn-secondary !bg-white/10 !text-white !border-white/20" onClick={load}><RefreshCw size={15}/>Refresh intelligence</button></div></div><div className="next-action"><div className="label">Career signal</div><div className="flex items-center gap-4 mt-3"><ScoreRing value={readiness.overall_score||0} size={92}/><div><h3>{readiness.verdict||'Build your signal'}</h3><p>Readiness is a moving target. Improve the weakest dimension first.</p></div></div></div></section>
  <div className="dashboard-grid"><Card><SectionHeading eyebrow="Career Twin" title={twin.headline||'Your professional identity'} description={twin.identity_statement||'Generate your Career Twin from your assessment and profile.'}/><div className="grid md:grid-cols-2 gap-5"><div><h4 className="font-extrabold mb-3">Strengths</h4><div className="flex flex-wrap gap-2">{(twin.strengths||[]).map(x=><Badge key={x} tone="primary">{x}</Badge>)}</div></div><div><h4 className="font-extrabold mb-3">Best environments</h4><ul className="list-clean">{(twin.best_fit_environments||[]).slice(0,4).map(x=><li key={x}><span className="dot"/>{x}</li>)}</ul></div></div><div className="ai-strip mt-5"><strong>90-day direction</strong><p className="text-sm text-gray-600">{(twin.next_90_days||['Complete your assessment and build one proof project.']).slice(0,3).join(' · ')}</p></div></Card><Card><SectionHeading eyebrow="Readiness" title="Know what is holding you back" description="A transparent score is more useful when every point has an explanation."/><div className="flex items-center gap-5 mb-6"><ScoreRing value={readiness.overall_score||0}/><div><div className="text-2xl font-black">{Math.round(readiness.overall_score||0)}/100</div><p className="text-sm text-gray-500">Overall career readiness</p></div></div><div className="space-y-4">{dimensions.slice(0,5).map(d=><ProgressBar key={d.name} value={d.score} label={d.name}/>)}</div></Card></div>
  <Card><SectionHeading eyebrow="Career Path" title={journey.current_stage||'Your next stage'} description={journey.north_star||'Your path is designed to compound evidence, skills and confidence.'} action={<Link className="arrow-link" to="/career/journey">View full path <ArrowRight size={15}/></Link>}/><div className="timeline">{(journey.stages||[]).map((s,i)=><div key={s.name} className={`timeline-node ${s.status==='done'?'done':''} ${s.status==='current'?'current':''}`}><div className="timeline-dot">{s.status==='done'?<ShieldCheck size={19}/>:s.status==='current'?<Zap size={19}/>:<span>{i+1}</span>}</div><div><strong>{s.name}</strong><span>{s.status==='current'?'Current focus':s.status==='done'?'Completed':'Up next'}</span></div></div>)}</div></Card>
  <div className="dashboard-grid"><Card><SectionHeading eyebrow="Opportunity Radar" title="Where your signal meets the market" description="Prioritize opportunities with a clear reason, not just a high number." action={<Link className="arrow-link" to="/jobs">Explore jobs <ArrowRight size={15}/></Link>}/>{data.radar?.opportunities?.length?<div className="space-y-3">{data.radar.opportunities.slice(0,4).map((o,i)=><div key={o.title||i} className="flex items-center justify-between gap-4 border-b last:border-0 pb-3 last:pb-0"><div><strong>{o.title}</strong><p className="text-xs text-gray-500 mt-1">{o.reason}</p></div><Badge tone="success">{Math.round(o.fit_score)}% fit</Badge></div>)}</div>:<div className="ai-strip"><strong>Radar ready</strong><p className="text-sm text-gray-600">Scan the job market from your Career Journey to surface your best opportunities.</p></div>}</Card><Card><SectionHeading eyebrow="What-if Lab" title="Test a career decision" description="Explore trade-offs before you invest your time."/><div className="flex gap-2"><input aria-label="Career what-if scenario" value={scenario} onChange={e=>setScenario(e.target.value)} placeholder="e.g. Learn SQL + build two analytics projects" className="flex-1 px-4 py-3 border border-gray-200 rounded-xl bg-gray-50 focus:bg-white focus:border-purple-300 outline-none"/><Button disabled={busy==='whatif'} onClick={simulate}>{busy==='whatif'?'Running...':'Simulate'}</Button></div>{data.simulation&&<div className="mt-5 grid grid-cols-2 gap-3"><div className="ai-strip"><span className="text-xs text-gray-500">Projected readiness</span><div className="text-2xl font-black text-primary mt-1">{Math.round(data.simulation.projected_score)}%</div></div><div className="ai-strip"><span className="text-xs text-gray-500">Trade-off</span><div className="text-sm font-semibold mt-1">{data.simulation.tradeoffs?.[0]||'Review assumptions'}</div></div></div>}</Card></div>
  <Card><SectionHeading eyebrow="Action map" title="Everything is connected"/><div className="grid md:grid-cols-4 gap-3">{[['Assessment','/career/assessment',Target],['Skill gap','/career/skills',Brain],['Roadmap','/career/roadmap',Route],['Interview','/career/interview',Sparkles]].map(([label,to,Icon])=><Link className="job-card" to={to} key={label}><Icon className="text-primary" size={20}/><h3>{label}</h3><p className="text-xs text-gray-500">Turn insight into action.</p></Link>)}</div></Card>
 </Container></Page>
}
