import { useEffect,useState } from 'react'
import { useParams,useNavigate,Link } from 'react-router-dom'
import { MapPin,Briefcase,DollarSign,Clock,ArrowLeft,Bookmark,BookmarkCheck,CheckCircle,Sparkles,Target,Brain,ArrowRight,AlertTriangle } from 'lucide-react'
import { supabase } from '../config/supabase'
import { useAuth } from '../context/AuthContext'
import { apiFetch } from '../lib/api'
import { Page,Container,Card,Eyebrow,Button,Badge,ProgressBar,Skeleton } from '../components/common/UI'
export default function JobDetail(){
 const {id}=useParams();const {user,profile}=useAuth();const nav=useNavigate();const [job,setJob]=useState(null);const [saved,setSaved]=useState(false);const [applied,setApplied]=useState(false);const [ai,setAi]=useState({});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [form,setForm]=useState({coverLetter:'',resumeUrl:''});
 useEffect(()=>{load()},[id,user])
 const load=async()=>{setLoading(true);const {data}=await supabase.from('jobs').select('*').eq('id',id).single();setJob(data);if(user){const [s,a]=await Promise.all([supabase.from('saved_jobs').select('id').eq('job_id',id).eq('user_id',user.id).maybeSingle(),supabase.from('applications').select('id').eq('job_id',id).eq('user_id',user.id).maybeSingle()]);setSaved(!!s.data);setApplied(!!a.data)}setLoading(false)}
 const analyze=async()=>{setBusy(true);setError('');const [m,g]=await Promise.all([apiFetch(`/ai-career/jobs/${id}/match`).catch(e=>({error:e.message})),apiFetch(`/ai-career/jobs/${id}/gap`).catch(e=>({error:e.message}))]);setAi({match:m?.match,gap:g?.gap});if(m?.error&&!g?.gap)setError('AI analysis is temporarily unavailable. The job itself is still available.');setBusy(false)}
 const toggleSave=async()=>{if(!user){nav('/login');return}if(saved)await supabase.from('saved_jobs').delete().eq('job_id',id).eq('user_id',user.id);else await supabase.from('saved_jobs').insert({job_id:id,user_id:user.id});setSaved(!saved)}
 const apply=async e=>{e.preventDefault();if(!user){nav('/login');return}setBusy(true);setError('');const {error}=await supabase.from('applications').insert({job_id:id,user_id:user.id,cover_letter:form.coverLetter,resume_url:form.resumeUrl||profile?.resume_url,status:'pending'});if(error)setError(error.message);else setApplied(true);setBusy(false)}
 if(loading)return <Page><Container><Skeleton className="h-96"/></Container></Page>;if(!job)return <Page><Container><Card>Job not found.</Card></Container></Page>
 return <Page><Container><Link to="/jobs" className="arrow-link mb-5"><ArrowLeft size={16}/>Back to marketplace</Link><div className="grid lg:grid-cols-[1.3fr_.7fr] gap-5"><div className="space-y-5"><Card><div className="flex flex-wrap justify-between gap-4"><div><Badge tone="primary">{job.job_type?.replace('-',' ')}</Badge><h1 className="text-4xl font-black tracking-tight mt-4">{job.title}</h1><p className="text-lg text-gray-500 mt-2">{job.company_name}</p></div><button onClick={toggleSave} className="ui-btn ui-btn-secondary h-fit">{saved?<BookmarkCheck size={17} className="text-primary"/>:<Bookmark size={17}/>} {saved?'Saved':'Save'}</button></div><div className="job-meta mt-6"><span><MapPin size={15}/>{job.location||'Flexible location'}</span><span><Briefcase size={15}/>{job.work_mode||'Flexible'}</span>{(job.salary_min||job.salary_max)&&<span><DollarSign size={15}/>{job.salary_min&&job.salary_max?`${job.salary_min.toLocaleString()} - ${job.salary_max.toLocaleString()}`:job.salary_min||job.salary_max}</span>}</div><div className="mt-7 pt-6 border-t border-gray-100"><h2 className="text-xl font-black">About the role</h2><p className="text-gray-600 leading-7 mt-3 whitespace-pre-wrap">{job.description||'Role details are provided by the hiring company.'}</p></div></Card>
 <Card><div className="flex flex-wrap justify-between items-center gap-3"><div><Eyebrow icon={Sparkles}>Explainable AI</Eyebrow><h2 className="text-2xl font-black mt-1">Understand your fit</h2><p className="text-sm text-gray-500 mt-1">Match score + skill gap analysis, not a black box.</p></div><Button onClick={analyze} disabled={busy}>{busy?'Analyzing...':'Analyze my fit'}</Button></div>{error&&<div className="mt-4 p-3 rounded-xl bg-red-50 text-red-700 text-sm flex gap-2"><AlertTriangle size={16}/>{error}</div>}{ai.match&&<div className="mt-6 grid md:grid-cols-[150px_1fr] gap-6"><div className="text-center"><div className="text-5xl font-black text-primary">{Math.round(ai.match.overall_score)}%</div><div className="text-xs uppercase tracking-wider text-gray-400 font-bold mt-1">match</div><p className="text-sm text-gray-500 mt-2">{ai.match.verdict}</p></div><div className="space-y-4">{ai.match.factors?.slice(0,5).map(f=><ProgressBar key={f.name} value={f.score} label={f.name}/>)}</div></div>}{ai.gap&&<div className="mt-6 grid md:grid-cols-2 gap-4"><div className="ai-strip"><div className="flex items-center gap-2 font-black"><Brain size={16} className="text-primary"/>Strengths</div><ul className="list-clean mt-3">{(ai.gap.strengths||[]).slice(0,5).map(x=><li key={x}><span className="dot"/>{x}</li>)}</ul></div><div className="ai-strip"><div className="flex items-center gap-2 font-black"><Target size={16} className="text-primary"/>Skill gaps</div><ul className="list-clean mt-3">{(ai.gap.gaps||[]).slice(0,5).map(x=><li key={x.skill||x}><span className="dot"/>{x.skill||x}</li>)}</ul></div></div>}</Card></div>
 <aside className="space-y-5"><Card glow><Eyebrow icon={Sparkles}>Next best action</Eyebrow><h2 className="text-2xl font-black mt-2">{applied?'Application submitted':'Turn this match into an application.'}</h2><p className="text-indigo-100 mt-3 text-sm leading-6">Use the AI Application Copilot to tailor your application to this exact role.</p>{!applied&&<Link className="ui-btn ui-btn-primary bg-white !text-gray-900 w-full mt-5" to={`/career/application-copilot/${id}`}>Open Application Copilot <ArrowRight size={16}/></Link>}<Link className="ui-btn ui-btn-secondary !bg-white/10 !text-white !border-white/20 w-full mt-2" to="/career/interview">Practice interview <ArrowRight size={16}/></Link></Card><Card><Eyebrow icon={CheckCircle}>Apply</Eyebrow><h3 className="text-xl font-black mt-2">{applied?'You are in the pipeline.':'Ready to apply?'}</h3>{applied?<p className="text-sm text-gray-500 mt-2">Track this application from your dashboard.</p>:<form onSubmit={apply} className="mt-4 space-y-3"><textarea required value={form.coverLetter} onChange={e=>setForm({...form,coverLetter:e.target.value})} rows={5} placeholder="Short cover note (or generate one with Copilot)" className="w-full border border-gray-200 rounded-xl p-3 outline-none focus:border-purple-300"/><input value={form.resumeUrl} onChange={e=>setForm({...form,resumeUrl:e.target.value})} placeholder="Resume URL (optional)" className="w-full border border-gray-200 rounded-xl p-3 outline-none"/><Button className="w-full" disabled={busy}>{busy?'Submitting...':'Submit application'}</Button></form>}</Card></aside></div></Container></Page>
}
