import { useState,useEffect } from 'react'
import { Link,useSearchParams } from 'react-router-dom'
import { Search,MapPin,Briefcase,Filter,X,Bookmark,BookmarkCheck,Navigation,Sparkles,ArrowRight } from 'lucide-react'
import { supabase } from '../config/supabase'
import { useAuth } from '../context/AuthContext'
import { Page,Container,Card,Eyebrow,Button,Badge,Skeleton,SectionHeading } from '../components/common/UI'

export default function Jobs(){
 const [params,setParams]=useSearchParams();const [jobs,setJobs]=useState([]);const [categories,setCategories]=useState([]);const [saved,setSaved]=useState(new Set());const [loading,setLoading]=useState(true);const [show,setShow]=useState(false);const {user}=useAuth();
 const [filters,setFilters]=useState({search:params.get('search')||'',jobType:params.get('jobType')||'',workMode:params.get('workMode')||'',category:params.get('category')||'',location:params.get('location')||''})
 useEffect(()=>{load()},[params,user])
 const load=async()=>{setLoading(true);let q=supabase.from('jobs').select('*').eq('is_active',true).order('created_at',{ascending:false});if(filters.search)q=q.or(`title.ilike.%${filters.search}%,company_name.ilike.%${filters.search}%,description.ilike.%${filters.search}%`);if(filters.jobType)q=q.eq('job_type',filters.jobType);if(filters.workMode)q=q.eq('work_mode',filters.workMode);if(filters.category)q=q.eq('category',filters.category);if(filters.location)q=q.ilike('location',`%${filters.location}%`);const [jr,cr,sr]=await Promise.all([q,supabase.from('jobs').select('category').eq('is_active',true),user?supabase.from('saved_jobs').select('job_id').eq('user_id',user.id):Promise.resolve({data:[]})]);setJobs(jr.data||[]);setCategories([...new Set((cr.data||[]).map(x=>x.category).filter(Boolean))]);setSaved(new Set((sr.data||[]).map(x=>x.job_id)));setLoading(false)}
 const change=(k,v)=>{const f={...filters,[k]:v};setFilters(f);const p=new URLSearchParams();Object.entries(f).forEach(([a,b])=>b&&p.set(a,b));setParams(p)}
 const clear=()=>{const f={search:'',jobType:'',workMode:'',category:'',location:''};setFilters(f);setParams({})}
 const toggle=async(id,e)=>{e.preventDefault();e.stopPropagation();if(!user)return; if(saved.has(id)){await supabase.from('saved_jobs').delete().eq('job_id',id).eq('user_id',user.id);setSaved(s=>{const n=new Set(s);n.delete(id);return n})}else{await supabase.from('saved_jobs').insert({job_id:id,user_id:user.id});setSaved(s=>new Set([...s,id]))}}
 return <Page><Container className="space-y-5"><section className="ui-card ui-card-glow"><div className="flex flex-wrap items-end justify-between gap-5"><div><Eyebrow icon={Sparkles}>Opportunity Radar</Eyebrow><h1 className="text-4xl font-black tracking-tight mt-2">Find the roles worth your attention.</h1><p className="text-indigo-100 mt-3 max-w-2xl">Search the live marketplace, then use AI Match and Skill Gap analysis to understand what to do next.</p></div><Link to="/jobs-near-me" className="ui-btn ui-btn-secondary !bg-white/10 !text-white !border-white/20"><Navigation size={16}/>Jobs near me</Link></div><div className="mt-7 flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={19}/><input aria-label="Search jobs" value={filters.search} onChange={e=>change('search',e.target.value)} placeholder="Search role, company, skill or keyword" className="w-full pl-11 pr-4 py-3.5 rounded-xl bg-white text-gray-900 border-0 outline-none"/></div><Button variant="secondary" onClick={()=>setShow(!show)}><Filter size={17}/>Filters {Object.values(filters).filter(Boolean).length>0&&<Badge tone="primary">{Object.values(filters).filter(Boolean).length}</Badge>}</Button></div>{show&&<div className="mt-4 p-4 rounded-xl bg-white/10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">{[['jobType','Job type',['','internship','full-time','part-time']],['workMode','Work mode',['','remote','on-site','hybrid']],['category','Category',['',...categories]]].map(([k,l,opts])=><label className="text-white text-xs font-bold" key={k}>{l}<select value={filters[k]} onChange={e=>change(k,e.target.value)} className="mt-1 w-full rounded-lg px-3 py-2.5 text-gray-900"><option value="">All</option>{opts.slice(1).map(o=><option key={o} value={o}>{o.replace('-',' ')}</option>)}</select></label>)}<label className="text-white text-xs font-bold">Location<input value={filters.location} onChange={e=>change('location',e.target.value)} className="mt-1 w-full rounded-lg px-3 py-2.5 text-gray-900" placeholder="City or region"/></label><button onClick={clear} className="text-left text-sm text-indigo-100 font-bold self-end">Clear filters <X size={15} className="inline"/></button></div>}</section>
 <div className="flex justify-between items-center"><div><Eyebrow>Live marketplace</Eyebrow><p className="text-sm text-gray-500 mt-1">{jobs.length} opportunities matching your search</p></div></div>
 {loading?<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{[1,2,3,4,5,6].map(i=><Skeleton key={i} className="h-64"/>)}</div>:jobs.length===0?<Card className="text-center py-16"><Briefcase className="mx-auto text-gray-300" size={48}/><h2 className="text-xl font-black mt-4">No matching roles</h2><p className="text-gray-500 mt-2">Try a broader keyword or remove a filter.</p><Button variant="secondary" className="mt-5" onClick={clear}>Reset search</Button></Card>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{jobs.map(job=><Link to={`/jobs/${job.id}`} key={job.id} className="job-card group"><div className="flex items-center justify-between gap-3"><Badge tone="primary">{job.job_type?.replace('-',' ')||'opportunity'}</Badge>{user&&<button aria-label={saved.has(job.id)?'Remove saved job':'Save job'} onClick={e=>toggle(job.id,e)} className="p-2 rounded-lg hover:bg-gray-100">{saved.has(job.id)?<BookmarkCheck className="text-primary" size={18}/>:<Bookmark className="text-gray-400" size={18}/>}</button>}</div><h3>{job.title}</h3><p className="text-sm font-semibold text-gray-600">{job.company_name}</p><div className="job-meta mt-4"><span><MapPin size={13}/>{job.location||'Flexible'}</span><span><Briefcase size={13}/>{job.work_mode||'Flexible'}</span></div><div className="mt-5 ai-strip"><div className="flex items-center gap-2 text-primary text-xs font-black"><Sparkles size={13}/>AI MATCH</div><p className="text-xs text-gray-500 mt-1">Analyze your fit, strengths and skill gaps</p></div><div className="job-footer"><span className="text-xs font-bold text-gray-500">View role intelligence</span><ArrowRight size={16} className="text-primary"/></div></Link>)}</div>}
 </Container></Page>
}
