export const demoJobs = [
  { id: 'demo-job-1', title: 'Frontend Developer Intern', company_name: 'Systems Limited', location: 'Lahore, Pakistan', city: 'Lahore', country: 'Pakistan', category: 'Web Development', job_type: 'internship', work_mode: 'hybrid', description: 'Build modern web interfaces with React and JavaScript.', salary_min: 25000, salary_max: 45000, latitude: 31.5204, longitude: 74.3587, is_active: true, status: 'active', created_at: '2026-08-26T08:00:00.000Z' },
  { id: 'demo-job-2', title: 'Software Engineer', company_name: '10Pearls', location: 'Islamabad, Pakistan', city: 'Islamabad', country: 'Pakistan', category: 'Software Engineering', job_type: 'full-time', work_mode: 'on-site', description: 'Develop scalable software products and APIs.', salary_min: 120000, salary_max: 220000, latitude: 33.6844, longitude: 73.0479, is_active: true, status: 'active', created_at: '2026-08-25T08:00:00.000Z' },
  { id: 'demo-job-3', title: 'Data Analyst', company_name: 'NETSOL Technologies', location: 'Lahore, Pakistan', city: 'Lahore', country: 'Pakistan', category: 'Data Science', job_type: 'full-time', work_mode: 'hybrid', description: 'Analyze business data and create dashboards.', salary_min: 90000, salary_max: 160000, latitude: 31.4697, longitude: 74.2728, is_active: true, status: 'active', created_at: '2026-08-24T08:00:00.000Z' },
  { id: 'demo-job-4', title: 'UI/UX Designer', company_name: 'Arbisoft', location: 'Lahore, Pakistan', city: 'Lahore', country: 'Pakistan', category: 'UI/UX', job_type: 'full-time', work_mode: 'remote', description: 'Design user-centered digital experiences.', salary_min: 80000, salary_max: 150000, latitude: 31.5497, longitude: 74.3436, is_active: true, status: 'active', created_at: '2026-08-23T08:00:00.000Z' },
  { id: 'demo-job-5', title: 'Marketing Intern', company_name: 'Daraz', location: 'Karachi, Pakistan', city: 'Karachi', country: 'Pakistan', category: 'Marketing', job_type: 'internship', work_mode: 'on-site', description: 'Support digital marketing and growth campaigns.', salary_min: 20000, salary_max: 35000, latitude: 24.8607, longitude: 67.0011, is_active: true, status: 'active', created_at: '2026-08-22T08:00:00.000Z' },
  { id: 'demo-job-6', title: 'Backend Developer', company_name: 'TRG Pakistan', location: 'Karachi, Pakistan', city: 'Karachi', country: 'Pakistan', category: 'Software Engineering', job_type: 'full-time', work_mode: 'hybrid', description: 'Build APIs and backend services.', salary_min: 110000, salary_max: 200000, latitude: 24.9068, longitude: 67.0822, is_active: true, status: 'active', created_at: '2026-08-21T08:00:00.000Z' },
]

export const demoCareers = [
  { id: 'career-software', title: 'Software Engineer', description: 'Design, build and maintain software applications.', category: 'Technology', required_skills: ['Programming', 'Problem Solving', 'JavaScript', 'React', 'Git', 'SQL'], recommended_skills: ['Node.js', 'APIs', 'Cloud'], is_active: true },
  { id: 'career-data', title: 'Data Scientist', description: 'Use data, statistics and machine learning to solve business problems.', category: 'Data Science', required_skills: ['Python', 'Statistics', 'SQL', 'Data Analysis'], recommended_skills: ['Machine Learning', 'Pandas', 'TensorFlow'], is_active: true },
  { id: 'career-ux', title: 'UI/UX Designer', description: 'Create useful, accessible and engaging digital experiences.', category: 'Design', required_skills: ['UI Design', 'UX Design', 'Research', 'Figma'], recommended_skills: ['Prototyping', 'Design Systems', 'Accessibility'], is_active: true },
  { id: 'career-marketing', title: 'Digital Marketing Specialist', description: 'Plan and optimize digital campaigns and content.', category: 'Marketing', required_skills: ['SEO', 'Content Marketing', 'Analytics'], recommended_skills: ['Google Ads', 'Social Media', 'Email Marketing'], is_active: true },
]

export const demoCounselors = [
  { id: 'counselor-1', full_name: 'Dr. Sarah Ahmed', email: 'sarah.ahmed@example.com', title: 'Senior Career Counselor', specializations: ['Software Engineering', 'Data Science'], years_of_experience: 12, rating: 4.9, hourly_rate: 80, availability: { monday: ['09:00-17:00'], tuesday: ['09:00-17:00'], wednesday: ['09:00-17:00'], thursday: ['09:00-17:00'], friday: ['09:00-17:00'] }, total_sessions: 420, is_verified: true, is_available: true },
  { id: 'counselor-2', full_name: 'Ali Hassan', email: 'ali.hassan@example.com', title: 'Technology Career Advisor', specializations: ['Product Management', 'UX Design'], years_of_experience: 8, rating: 4.8, hourly_rate: 65, availability: { monday: ['10:00-18:00'], tuesday: ['10:00-18:00'], wednesday: ['10:00-18:00'], thursday: ['10:00-18:00'], friday: ['10:00-18:00'] }, total_sessions: 260, is_verified: true, is_available: true },
  { id: 'counselor-3', full_name: 'Maria Khan', email: 'maria.khan@example.com', title: 'Business & Marketing Coach', specializations: ['Marketing', 'Business Analysis'], years_of_experience: 10, rating: 4.8, hourly_rate: 70, availability: { monday: ['14:00-20:00'], tuesday: ['14:00-20:00'], wednesday: ['14:00-20:00'], thursday: ['14:00-20:00'], friday: ['14:00-20:00'], saturday: ['14:00-20:00'] }, total_sessions: 310, is_verified: true, is_available: true },
  { id: 'counselor-4', full_name: 'Farhan Malik', email: 'farhan.malik@example.com', title: 'Engineering Career Specialist', specializations: ['Engineering', 'Technical Skills'], years_of_experience: 9, rating: 4.7, hourly_rate: 60, availability: { monday: ['09:00-17:00'], tuesday: ['09:00-17:00'], wednesday: ['09:00-17:00'], thursday: ['09:00-17:00'], friday: ['09:00-17:00'] }, total_sessions: 230, is_verified: true, is_available: true },
  { id: 'counselor-5', full_name: 'Aisha Raza', email: 'aisha.raza@example.com', title: 'Finance & Leadership Coach', specializations: ['Finance', 'Leadership'], years_of_experience: 11, rating: 4.9, hourly_rate: 75, availability: { monday: ['10:00-18:00'], tuesday: ['10:00-18:00'], wednesday: ['10:00-18:00'], thursday: ['10:00-18:00'], friday: ['10:00-18:00'] }, total_sessions: 350, is_verified: true, is_available: true },
]

export const demoStore = { assessments: new Map(), matches: new Map(), skills: new Map(), roadmaps: new Map(), sessions: new Map(), profiles: new Map(), careerTwins: new Map(), interviews: new Map() }
